import {useState,type ReactNode} from 'react';
import {allowReminders,ReminderPermissionHelp} from './NotificationNotice';
import {errorMessage} from './asset';
import {FormRow,Switch,Segments,ChoiceField,CentInput} from './FormControls';
import {DateInput} from './DateInput';
import {localDay} from './asset';
import type {AssetOptions} from './preferences';
export function AssetOptionsFields({options,onChange,generation,disabled,existing,purchaseDate,children}:{options:AssetOptions;onChange:(v:AssetOptions)=>void;generation:string;disabled:boolean;existing:boolean;purchaseDate:string;children?:ReactNode}){
 const [reminderError,setReminderError]=useState(''),[permissionPending,setPermissionPending]=useState(false);
 async function enableReminder(){onChange({...options,warranty:{...options.warranty!,reminder:{date:options.warranty!.end_date,notes:''}}});setReminderError('');setPermissionPending(true);try{await allowReminders()}catch(e){setReminderError(errorMessage(e))}finally{setPermissionPending(false)}}
 const p=options.preferences,update=(v:Partial<typeof p>)=>onChange({...options,preferences:{...p,...v}});
 return <><ReminderPermissionHelp pending={!!options.warranty?.reminder&&permissionPending} error={!!options.warranty?.reminder?reminderError:''}/><section className="form-block"><FormRow label="成本计算模式"><Segments label="成本计算模式" value={p.cost_mode} options={[{value:'daily',label:'按日计算'},{value:'per_use',label:'按次计算'}]} disabled={disabled} onChange={cost_mode=>update({cost_mode})}/></FormRow>{p.cost_mode==='per_use'&&<FormRow label="已使用次数" hint="未记录次数时，单次成本待补充"><input aria-label="已使用次数" type="number" min="0" max="1000000000" step="1" value={p.use_count} disabled={disabled} onChange={e=>update({use_count:Math.max(0,Math.trunc(Number(e.target.value)))})}/></FormRow>}<FormRow label="目标设定"><Segments label="目标设定" value={p.goal.mode} options={[{value:'none',label:'不设定'},{value:'cost',label:'按价格'},{value:'date',label:'按日期'}]} disabled={disabled} onChange={mode=>update({goal:mode==='cost'?{mode,cents:''}:mode==='date'?{mode,date:''}:{mode}})}/></FormRow>{p.goal.mode==='cost'&&<FormRow label="目标单位成本（元）"><CentInput label="目标单位成本" placeholder="请输入目标成本" disabled={disabled} value={p.goal.cents} onChange={cents=>update({goal:{mode:'cost',cents}})}/></FormRow>}{p.goal.mode==='date'&&<FormRow label="目标日期"><DateInput label="目标日期" id="asset-goal-date" value={p.goal.date} onChange={date=>update({goal:{mode:'date',date}})} disabled={disabled}/></FormRow>}</section>
 {children}
 {!existing&&<><section className="form-block"><FormRow label="保障时间"><Switch label="设置保障时间" disabled={disabled} value={!!options.warranty} onChange={v=>onChange({...options,warranty:v?{start_date:purchaseDate||null,end_date:localDay(),reminder:null}:null})}/></FormRow>{options.warranty&&<><FormRow label="保障结束日期"><DateInput label="保障结束日期" id="asset-warranty-end" value={options.warranty.end_date} disabled={disabled} onChange={end_date=>onChange({...options,warranty:{...options.warranty!,end_date}})}/></FormRow><FormRow label="启用保障到期提醒" hint="所选日期上午 9:00 通知"><Switch label="启用保障到期提醒" value={!!options.warranty.reminder} disabled={disabled} onChange={v=>{if(!v)onChange({...options,warranty:{...options.warranty!,reminder:null}});else void enableReminder()}}/></FormRow>{options.warranty.reminder&&<><FormRow label="提醒日期"><DateInput label="提醒日期" id="asset-reminder-date" value={options.warranty.reminder.date} disabled={disabled} onChange={date=>onChange({...options,warranty:{...options.warranty!,reminder:{...options.warranty!.reminder!,date}}})}/></FormRow><FormRow label="提醒备注"><input aria-label="提醒备注" value={options.warranty.reminder.notes} disabled={disabled} onChange={e=>onChange({...options,warranty:{...options.warranty!,reminder:{...options.warranty!.reminder!,notes:e.target.value}}})}/></FormRow></>}</>}</section><section className="form-block"><FormRow label="已退役"><Switch label="已退役" disabled={disabled} value={!!options.retired_date} onChange={v=>onChange({...options,retired_date:v?localDay():null})}/></FormRow>{options.retired_date&&<FormRow label="退役日期"><DateInput label="退役日期" id="asset-retired-date" value={options.retired_date} max={localDay()} disabled={disabled} onChange={retired_date=>onChange({...options,retired_date})}/></FormRow>}<FormRow label="已售出"><Switch label="已售出" disabled={disabled} value={!!options.sale} onChange={v=>onChange({...options,sale:v?{date:localDay(),price_cents:'',platform:'',buyer:'',notes:''}:null})}/></FormRow>{options.sale&&<><FormRow label="售出价格（元）"><CentInput label="售出价格" placeholder="请输入售出价格" disabled={disabled} value={options.sale.price_cents} onChange={price_cents=>onChange({...options,sale:{...options.sale!,price_cents}})}/></FormRow><FormRow label="售出渠道"><ChoiceField kind="sale_channel" label="售出渠道" value={options.sale.platform||null} onChange={platform=>onChange({...options,sale:{...options.sale!,platform:platform||''}})} generation={generation} byName disabled={disabled}/></FormRow><FormRow label="售出日期"><DateInput label="售出日期" id="asset-sold-date" value={options.sale.date} max={localDay()} disabled={disabled} onChange={date=>onChange({...options,sale:{...options.sale!,date}})}/></FormRow></>}</section></>}
 <section className="form-block"><FormRow label="置顶物品"><Switch label="置顶物品" value={p.pinned} disabled={disabled} onChange={pinned=>update({pinned})}/></FormRow></section><section className="form-block"><FormRow label="不计入统计"><Switch label="不计入统计" value={Object.values(p.exclude).some(Boolean)} disabled={disabled} onChange={v=>update({exclude:{total:v,daily:v,statistics:v,timeline:v}})}/></FormRow>{Object.values(p.exclude).some(Boolean)&&<div className="exclusion-grid">{(['total','daily','statistics','timeline'] as const).map((k,i)=><label key={k}><input type="checkbox" checked={p.exclude[k]} disabled={disabled} onChange={e=>update({exclude:{...p.exclude,[k]:e.target.checked}})}/>{['不计入总金额','不计入日均成本','不计入统计页面','不在时间轴显示'][i]}</label>)}</div>}</section></>;
}
