import {useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {errorMessage} from './asset';
export function FormRow({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <div className="form-row"><div className="form-row-label">{label}{hint&&<small>{hint}</small>}</div><div className="form-row-control">{children}</div></div>}
export function Switch({label,value,onChange,disabled}:{label:string;value:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <button type="button" role="switch" aria-label={label} aria-checked={value} disabled={disabled} className="form-switch" onClick={()=>onChange(!value)}><span/></button>}
export function Segments<T extends string>({label,value,options,onChange,disabled}:{label:string;value:T;options:readonly {value:T;label:string}[];onChange:(v:T)=>void;disabled?:boolean}){return <div className="form-segments" role="group" aria-label={label} style={{'--segments':options.length,'--selected':Math.max(0,options.findIndex(o=>o.value===value))} as CSSProperties}><span className="segment-thumb"/>{options.map(o=><button type="button" key={o.value} aria-pressed={value===o.value} disabled={disabled} onClick={()=>onChange(o.value)}>{o.label}</button>)}</div>}
export function DragHandle({label,disabled,onDrop,onStep}:{label:string;disabled?:boolean;onDrop:(id:string)=>void;onStep:(direction:-1|1)=>void}){
 const drag=useRef<{source:HTMLElement;ghost:HTMLElement;target:HTMLElement|null;startX:number;startY:number;left:number;top:number}|null>(null);
 function clear(){const active=drag.current;if(!active)return;active.source.classList.remove('sort-origin');active.target?.classList.remove('sort-target');active.ghost.remove();drag.current=null}
 useEffect(()=>clear,[]);
 return <button type="button" className="drag-handle" aria-label={'拖动排序：'+label} title="拖动排序；聚焦后用上下方向键移动" disabled={disabled} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();onStep(e.key==='ArrowUp'?-1:1)}}} onPointerDown={e=>{if(disabled||e.button!==0)return;const source=e.currentTarget.closest<HTMLElement>('[data-sort-id]');if(!source)return;e.preventDefault();e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);const rect=source.getBoundingClientRect(),ghost=source.cloneNode(true) as HTMLElement;ghost.classList.add('sort-ghost');ghost.setAttribute('aria-hidden','true');ghost.inert=true;Object.assign(ghost.style,{width:rect.width+'px',height:rect.height+'px',left:rect.left+'px',top:rect.top+'px'});source.after(ghost);source.classList.add('sort-origin');drag.current={source,ghost,target:null,startX:e.clientX,startY:e.clientY,left:rect.left,top:rect.top}}} onPointerMove={e=>{const active=drag.current;if(!active)return;active.ghost.style.left=active.left+e.clientX-active.startX+'px';active.ghost.style.top=active.top+e.clientY-active.startY+'px';const target=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-sort-id]');if(target===active.target)return;active.target?.classList.remove('sort-target');active.target=target&&target!==active.source?target:null;active.target?.classList.add('sort-target')}} onPointerUp={e=>{const active=drag.current;if(!active)return;const id=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-sort-id]')?.getAttribute('data-sort-id');clear();if(id)onDrop(id)}} onPointerCancel={clear}><svg viewBox="0 0 20 20" aria-hidden="true">{[5,10,15].flatMap(y=>[7,13].map(x=><circle key={x+','+y} cx={x} cy={y} r="1.4"/>))}</svg></button>
}
export function SelectionMark(){return <span className="selection-mark" aria-hidden="true"><span/></span>}
type Entry={id:string;name:string;enabled:boolean};type Snapshot={revision:number;items:Entry[]};
export function ChoiceField({kind,label,value,onChange,generation,disabled,byName=false}:{kind:'category'|'channel'|'label'|'sale_channel';label:string;value:string|null;onChange:(v:string|null)=>void;generation:string;disabled?:boolean;byName?:boolean}){
 const [data,setData]=useState<Snapshot|null>(null),[open,setOpen]=useState(false),[manage,setManage]=useState(false),[name,setName]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const panel=useRef<HTMLDialogElement>(null),pending=useRef<unknown>(null);
 const empty=kind==='category'?'全部':kind==='label'?'未设置':'未选择';
 const load=()=>invoke<Snapshot>('choice_list',{kind}).then(setData).catch(e=>setNotice(errorMessage(e)));
 useEffect(()=>{void load()},[kind,generation]);useEffect(()=>{if(open)panel.current?.showModal();else panel.current?.close()},[open]);useEffect(()=>{panel.current?.querySelector('.choice-body')?.scrollTo(0,0)},[manage]);
 async function change(action:unknown){if(!data||busy)return;setBusy(true);const input=pending.current??{request_id:crypto.randomUUID(),generation,expected_revision:data.revision,kind,action};pending.current=input;try{setData(await invoke<Snapshot>('choice_change',{input}));pending.current=null;setName('');setNotice('');window.dispatchEvent(new Event('possio-choices-changed'));}catch(e){setNotice(errorMessage(e));if((e as {code?:string})?.code!=='WORKER'){pending.current=null;void load()}}finally{setBusy(false)}}
 function move(id:string,to:number){if(!data)return;const ids=data.items.map(i=>i.id),from=ids.indexOf(id);ids.splice(from,1);ids.splice(to,0,id);void change({type:'reorder',ids})}
 const selected=data?.items.find(e=>(byName?e.name:e.id)===value);
 return <><button className="choice-trigger" type="button" disabled={disabled} aria-label={label} onClick={()=>{setOpen(true);void load()}}>{selected?.name||value||empty}<svg className="choice-chevron" viewBox="0 0 20 20" aria-hidden="true"><path d="m6 8 4 4 4-4"/></svg></button>{open&&<dialog ref={panel} className="editor choice-dialog" aria-label={(manage?'管理':'选择')+label} onCancel={e=>{e.preventDefault();if(!busy&&!pending.current)setOpen(false)}}><header><h2>{manage?'管理':'选择'}{label}</h2><button type="button" disabled={busy||!!pending.current} onClick={()=>setOpen(false)} aria-label="关闭选项">×</button></header><div className="choice-body"><p className="muted small">{manage?'拖动左侧手柄排序；键盘可用上下方向键。停用不影响已有记录。':kind==='label'?'自定义标签独立保存；保障、退役和售出按真实记录自动显示。':'选择一项；可以在管理中添加和整理。'}</p><div className="choice-list">{!manage&&<button type="button" aria-pressed={!value} onClick={()=>{onChange(null);setOpen(false)}}>{empty}<SelectionMark/></button>}{data?.items.filter(e=>manage||e.enabled||(byName?e.name:e.id)===value).map((e,i)=><div key={e.id} className="choice-item" data-sort-id={e.id}>{manage?<><DragHandle label={e.name} disabled={busy||!!pending.current} onDrop={id=>{const to=data!.items.findIndex(item=>item.id===id);if(to>=0&&to!==i)move(e.id,to)}} onStep={direction=>{const to=i+direction;if(to>=0&&to<data!.items.length)move(e.id,to)}}/><span>{e.name}</span><Switch label={'启用'+e.name} value={e.enabled} disabled={busy||!!pending.current} onChange={enabled=>void change({type:'enable',id:e.id,enabled})}/></>:<button type="button" aria-pressed={value===(byName?e.name:e.id)} onClick={()=>{onChange(byName?e.name:e.id);setOpen(false)}}>{e.name}{!e.enabled&&'（已停用）'}<SelectionMark/></button>}</div>)}</div>{manage&&<div className="choice-create"><input onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();if(name.trim()&&!busy&&!pending.current)void change({type:'create',name})}}} aria-label={'新'+label+'名称'} placeholder={'输入'+label+'名称'} value={name} disabled={busy||!!pending.current} onChange={e=>setName(e.target.value)}/><button type="button" disabled={!name.trim()||busy||!!pending.current} onClick={()=>void change({type:'create',name})}>创建</button></div>}{notice&&<p className="error" role="alert">{notice}</p>}</div><footer className="actions">{!!pending.current&&<button type="button" disabled={busy} onClick={()=>void change(null)}>重试本次操作</button>}<button type="button" disabled={busy||!!pending.current} onClick={()=>setManage(!manage)}>{manage?'完成管理':'管理'}</button></footer></dialog>}</>;
}
export function AddImageButton({onClick,disabled}:{onClick:()=>void;disabled?:boolean}){return <button type="button" className="add-image-button" onClick={onClick} disabled={disabled}><svg viewBox="0 0 40 40" aria-hidden="true"><rect className="album-back" x="5" y="5" width="25" height="29" rx="5" transform="rotate(-8 17 20)"/><rect className="album-front" x="8" y="8" width="26" height="27" rx="5"/><circle className="album-sun" cx="16" cy="16" r="3"/><path className="album-hill" d="m10 29 7-8 5 5 4-5 6 8v4H10Z"/><circle className="album-plus" cx="32" cy="9" r="7"/><path className="album-plus-line" d="M32 6v6M29 9h6"/></svg><span>添加图片</span></button>}
export function CentInput({label,value,onChange,disabled,placeholder}:{label:string;value:string;onChange:(v:string)=>void;disabled?:boolean;placeholder?:string}){const [raw,setRaw]=useState(value===''?'':String(Number(value)/100));useEffect(()=>{const normalized=raw===''?'':String(Math.round(Number(raw)*100));if(normalized!==value)setRaw(value===''?'':String(Number(value)/100))},[value]);return <input aria-label={label} inputMode="decimal" placeholder={placeholder} disabled={disabled} value={raw} onChange={e=>{const next=e.target.value;if(!/^\d{0,9}(\.\d{0,2})?$/.test(next))return;setRaw(next);const [whole,fraction='']=next.split('.');onChange(next===''?'':(BigInt(whole||'0')*100n+BigInt(fraction.padEnd(2,'0'))).toString())}}/>}
