import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {money,inputMoney,errorMessage,localDay} from './asset';
import {defaultWishPreferences,savingPercent} from './preferences';
import {PhotoView} from './Photos';
import {DefaultAssetIcon} from './IconPicker';
import {FormRow,Segments} from './FormControls';
import type {TaxonomySnapshot} from './taxonomy';
import type {CloseIntent} from './AssetEditor';
import type {WishlistItem} from './wishlist';
const key='possio.savings-pending.v1';
type Saving={request_id:string;generation:string;id:string;expected_revision:number;mode:'add'|'total';cents:string};
export function SavingsRing({item}:{item:WishlistItem}){const p=item.preferences??defaultWishPreferences(),v=savingPercent(p.saved_cents,item.fields.estimated_price_cents);return <span className="savings-ring" role="img" aria-label={`攒钱进度 ${v===null?'待设价格':v+'%'}`}><svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="20"/><circle cx="24" cy="24" r="20" pathLength="100" strokeDasharray={`${v??0} 100`}/></svg><b>{v===null?'—':v+'%'}</b></span>}
export function WishDetail({initial,generation,onClose,onEdit,onChange,onConvert,closeIntent,onKeepClose,onFinishClose,onOpenAsset,onOpenTrash,taxonomy}:{onOpenAsset:(id:string)=>void;onOpenTrash:()=>void;onFinishClose:(intent:CloseIntent)=>void;taxonomy:TaxonomySnapshot|null;closeIntent:CloseIntent|null;onKeepClose:()=>void;initial:WishlistItem;generation:string;onClose:()=>void;onEdit:(i:WishlistItem)=>void;onChange:(i:WishlistItem)=>void;onConvert:(i:WishlistItem)=>void}){
 const ref=useRef<HTMLDialogElement>(null),lock=useRef(false);
 const [item,setItem]=useState(initial),[amount,setAmount]=useState(''),[mode,setMode]=useState<'add'|'total'>('add'),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[pending,setPending]=useState<Saving|null>(()=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v?.generation===generation&&v?.id===initial.id?v:null}catch{return null}});
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);
 const p=item.preferences??defaultWishPreferences(),percent=savingPercent(p.saved_cents,item.fields.estimated_price_cents),remaining=item.fields.estimated_price_cents===null?null:(BigInt(item.fields.estimated_price_cents)>BigInt(p.saved_cents)?BigInt(item.fields.estimated_price_cents)-BigInt(p.saved_cents):0n).toString();
 async function save(value?:string){if(lock.current)return;if(!pending&&!value&&!amount.trim()){setNotice('请输入金额；更正为零时请填写 0。');return;}lock.current=true;setBusy(true);try{const input=pending??{request_id:crypto.randomUUID(),generation,id:item.id,expected_revision:item.revision,mode:value?'add':mode,cents:value??inputMoney(amount)??'0'};if(!pending&&mode==='add'&&input.cents==='0'){setNotice('请输入大于零的新增金额。');return}localStorage.setItem(key,JSON.stringify(input));setPending(input);try{const next=await invoke<WishlistItem>('save_wish_savings',{input});localStorage.removeItem(key);setPending(null);setItem(next);onChange(next);setAdding(false);setAmount('');setNotice(next.status!==item.status?next.status==='achieved'?'已攒够，心愿自动实现。':'累计金额不足目标，心愿已回到未实现。':'已保存这笔金额。')}catch(e){try{const saved=await invoke<WishlistItem|null>('saved_wish_feature',{request:input.request_id,generation});if(saved){localStorage.removeItem(key);setPending(null);setItem(saved);onChange(saved);setAdding(false);setNotice('已核对，金额已保存。')}else{localStorage.removeItem(key);setPending(null);setNotice(errorMessage(e))}}catch{setNotice('暂时无法核对结果，请重试同一笔金额。')}}}catch(e){setNotice(errorMessage(e))}finally{lock.current=false;setBusy(false)}}
 useEffect(()=>{if(closeIntent){if(busy||pending){setNotice('正在核对这笔金额，请稍候。');onKeepClose()}else{onClose();onFinishClose(closeIntent)}}},[closeIntent]);
 const blocked=busy||!!pending;
 return <dialog ref={ref} className="editor wish-detail" aria-labelledby="wish-detail-title" onCancel={e=>{e.preventDefault();if(!blocked)onClose()}}><header><button type="button" className="icon-button" disabled={blocked} aria-label="关闭心愿详情" onClick={onClose}>×</button><div className="wish-detail-identity">{item.cover?<PhotoView photo={item.cover} generation={generation}/>:<DefaultAssetIcon/>}<div><p className="eyebrow">{item.status==='achieved'?'已实现':'未实现'}</p><h2 id="wish-detail-title">{item.fields.name}</h2></div></div><div className="editor-header-actions"><button type="button" disabled={blocked} onClick={()=>onEdit(item)}>编辑</button>{!item.converted_asset&&<button type="button" disabled={blocked} onClick={()=>onConvert(item)}>已购入…</button>}</div></header>
 <div className="wish-detail-body">
 {p.mode==='savings'&&<section className="wish-funding"><div className="saving-summary"><span>已攒金额</span><strong>{money(p.saved_cents)}<small> / {money(item.fields.estimated_price_cents)}</small></strong><div className="saving-bar" role="progressbar" aria-label="攒钱总进度" aria-valuenow={percent??0} aria-valuemin={0} aria-valuemax={100}><span style={{width:(percent??0)+'%'}}/></div><small>{percent===null?'设置心愿价格后显示进度':`已完成 ${percent}%`} · 还差 {money(remaining)}</small></div><div className="savings-controls"><div className="quick-savings">{[1,5,10,100].map(n=><button type="button" key={n} disabled={blocked} onClick={()=>{setMode('add');void save(String(n*100))}}>+{n}</button>)}{[1,5,10].map(n=><button type="button" key={n+'%'} disabled={blocked||!item.fields.estimated_price_cents||item.fields.estimated_price_cents==='0'} onClick={()=>{setMode('add');void save(((BigInt(item.fields.estimated_price_cents!)*BigInt(n)+50n)/100n).toString())}}>+{n}%</button>)}</div>{adding&&<><Segments label="攒钱金额方式" value={mode} options={[{value:'add',label:'本次增加'},{value:'total',label:'更正累计'}]} disabled={blocked} onChange={setMode}/><input autoFocus aria-label={mode==='add'?'本次增加金额':'累计金额'} placeholder={mode==='add'?'请输入本次金额':'请输入累计金额'} inputMode="decimal" value={amount} disabled={blocked} onChange={e=>setAmount(e.target.value)}/></>}<button type="button" className="primary save-money-button" disabled={busy} onClick={()=>{if(pending||adding)void save();else{setAdding(true);setMode('add')}}}>{pending?'重试并核对本次金额':adding?'保存金额':'攒一笔'}</button></div></section>}
 <section className="form-block wish-facts"><FormRow label="心愿价格">{money(item.fields.estimated_price_cents)}</FormRow><FormRow label="添加时间">{p.added_date??localDay(new Date(item.created_at))}</FormRow><FormRow label="资产分类">{taxonomy?.categories.find(c=>c.id===item.fields.category_id)?.name||'全部'}</FormRow><FormRow label="购买渠道">{taxonomy?.channels.find(c=>c.id===p.channel_id)?.name||'未选择'}</FormRow><FormRow label="心愿状态">{item.status==='achieved'?'已实现':'未实现'}</FormRow><FormRow label="实现方式">{p.mode==='savings'?'攒钱':'倒计时'}</FormRow>{p.mode==='countdown'&&<FormRow label="目标实现时间">{item.fields.target_date||'未设置'}</FormRow>}{item.achieved_at&&<FormRow label="实现日期">{localDay(new Date(item.achieved_at))}</FormRow>}</section>
 {(item.fields.notes||item.fields.external_link||item.photos?.some(x=>x.id!==item.cover?.id))&&<section className="form-block form-notes wish-notes">{item.fields.notes&&<p className="notes">{item.fields.notes}</p>}{item.fields.external_link&&<a href={item.fields.external_link} target="_blank" rel="noreferrer">相关链接</a>}<div className="photo-strip">{item.photos?.filter(x=>x.id!==item.cover?.id).map(photo=><PhotoView key={photo.id} photo={photo} generation={generation}/>)}</div></section>}
 {item.converted_asset&&<p className="wishlist-link">关联资产：{item.converted_asset.name}{item.converted_asset.deleted?<button onClick={()=>{onClose();onOpenTrash()}}>前往最近删除</button>:<button onClick={()=>{onClose();onOpenAsset(item.converted_asset!.id)}}>查看资产</button>}</p>}</div>{notice&&<p className="notice" role="status">{notice}</p>}</dialog>
}
