import { DeleteButton, usePendingReceipt } from './WealthPage';
import { storedPending } from './wealth';
import { CloseButton } from './CloseButton';
import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {money,inputMoney,errorMessage,savingsErrorNotice,localDay} from './asset';
import {defaultWishPreferences,savingPercent} from './preferences';
import {PhotoView} from './Photos';
import {DefaultAssetIcon} from './IconPicker';
import {FormRow,Segments} from './FormControls';
import type {TaxonomySnapshot} from './taxonomy';
import type {CloseIntent} from './AssetEditor';
import type {WishlistItem} from './wishlist';
const key='possio.savings-pending.v1';
type Saving={request_id:string;generation:string;id:string;expected_revision:number;mode:'add'|'total';cents:string};
export function SavingsRing({item}:{item:WishlistItem}){const p=item.preferences??defaultWishPreferences(),v=savingPercent(p.saved_cents,item.fields.estimated_price_cents);return <span className="savings-ring" role="img" aria-label={`攒钱进度 ${v===null?'待设价格':v+'%'}`}><svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="20"/><circle cx="24" cy="24" r="20" pathLength="100" strokeDasharray={`${v??0} 100`}/></svg><b>{v===null?'—':v+'%'}</b></span>}
export function WishDetail({onBusyChange,onAbandon,onDeleted,initial,generation,onClose,onEdit,onChange,onConvert,closeIntent,onKeepClose,onFinishClose,onOpenAsset,onOpenTrash,taxonomy}:{onBusyChange:(busy:boolean)=>void;onAbandon:(item:WishlistItem)=>void;onDeleted:()=>void;onOpenAsset:(id:string)=>void;onOpenTrash:()=>void;onFinishClose:(intent:CloseIntent)=>void;taxonomy:TaxonomySnapshot|null;closeIntent:CloseIntent|null;onKeepClose:()=>void;initial:WishlistItem;generation:string;onClose:()=>void;onEdit:(i:WishlistItem)=>void;onChange:(i:WishlistItem)=>void;onConvert:(i:WishlistItem)=>void}){
 const lock=useRef(false);
 const receipt=usePendingReceipt(()=>{onChange(item);onClose()});
 const [deleting,setDeleting]=useState(false);
 const [item,setItem]=useState(initial),[amount,setAmount]=useState(''),[mode,setMode]=useState<'add'|'total'>('add'),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[pending,setPending]=useState<Saving|null>(()=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v?.generation===generation&&v?.id===initial.id?v:null}catch{return null}});
 useEffect(()=>{onBusyChange(busy||!!pending||deleting||!!receipt.pending||receipt.busy);return()=>onBusyChange(false)},[busy,pending,deleting,receipt.pending,receipt.busy,onBusyChange]);
 const noticeRef=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{if(notice)noticeRef.current?.scrollIntoView({block:'nearest'})},[notice]);
 const p=item.preferences??defaultWishPreferences(),percent=savingPercent(p.saved_cents,item.fields.estimated_price_cents),remaining=item.fields.estimated_price_cents===null?null:(BigInt(item.fields.estimated_price_cents)>BigInt(p.saved_cents)?BigInt(item.fields.estimated_price_cents)-BigInt(p.saved_cents):0n).toString();
 async function save(value?:string){if(lock.current)return;if(!pending&&item.status==='achieved'){setNotice('这条心愿已实现；如需更正，请编辑累计金额。');return}if(!pending&&!value&&!amount.trim()){setNotice('请输入金额；更正为零时请填写 0。');return;}lock.current=true;setBusy(true);try{const input=pending??{request_id:crypto.randomUUID(),generation,id:item.id,expected_revision:item.revision,mode:value?'add':mode,cents:value??inputMoney(amount)??'0'};if(!pending&&input.mode==='add'&&input.cents==='0'){setNotice('请输入大于零的新增金额。');return}localStorage.setItem(key,JSON.stringify(input));setPending(input);const finish=(next:WishlistItem)=>{localStorage.removeItem(key);setPending(null);setItem(next);onChange(next);setAdding(false);setAmount('');if(next.status==='achieved'&&next.preferences?.achievement_source==='savings'){onClose();return}setNotice(next.status!==item.status?'累计金额不足目标，心愿已回到未实现。':'已保存这笔金额。')};try{finish(await invoke<WishlistItem>('save_wish_savings',{input}))}catch(e){try{const saved=await invoke<WishlistItem|null>('saved_wish_feature',{request:input.request_id,generation});if(saved)finish(saved);else{localStorage.removeItem(key);setPending(null);setNotice(savingsErrorNotice(e))}}catch{setNotice('暂时无法核对结果，请重试同一笔金额。')}}}catch(e){setNotice(errorMessage(e))}finally{lock.current=false;setBusy(false)}}
 useEffect(()=>{if(closeIntent){if(busy||pending||deleting||receipt.pending||receipt.busy){setNotice('正在核对这笔金额，请稍候。');onKeepClose()}else{onClose();onFinishClose(closeIntent)}}},[closeIntent]);
 const blocked=busy||!!pending||deleting||!!receipt.pending||receipt.busy;
 return <aside className="ui-inspector wish-inspector" aria-labelledby="wish-detail-title"><header><CloseButton type="button" className="icon-button" disabled={blocked} aria-label="关闭心愿详情" onClick={onClose}/><div className="wish-detail-identity">{item.cover?<PhotoView photo={item.cover} generation={generation}/>:<DefaultAssetIcon/>}<div><p className="eyebrow">{item.status==='achieved'?'已实现':item.status==='abandoned'?'已放弃':'进行中'}</p><h2 id="wish-detail-title">{item.fields.name}</h2></div></div><details className="popover-menu" data-popover><summary aria-label="心愿更多操作">⋯</summary><div role="menu"><button type="button" disabled={blocked} onClick={()=>onEdit(item)}>编辑与提醒</button><DeleteButton label="删除心愿…" disabled={blocked} kind="wish" id={item.id} revision={item.revision} generation={generation} name={item.fields.name} onBusyChange={setDeleting} onDone={onDeleted} onError={message=>{setNotice(message);receipt.setPending(storedPending())}}/></div></details></header>
 <div className="wish-detail-body">{receipt.pending&&<div className="notice">删除结果待确认。<button disabled={receipt.busy} onClick={()=>void receipt.verify()}>核对结果</button></div>}
 {p.mode==='savings'&&<section className="wish-funding"><div className="saving-summary"><span>已攒金额</span><strong>{money(p.saved_cents)}<small> / {money(item.fields.estimated_price_cents)}</small></strong><div className="saving-bar" role="progressbar" aria-label="攒钱总进度" aria-valuenow={percent??0} aria-valuemin={0} aria-valuemax={100}><span style={{width:(percent??0)+'%'}}/></div><small>{percent===null?'设置心愿价格后显示进度':`已完成 ${percent}%`} · 还差 {money(remaining)}</small></div>{item.status==='ongoing'&&<div className="savings-controls"><div className="quick-savings">{[1,5,10,100].map(n=><button type="button" key={n} disabled={blocked} onClick={()=>{setMode('add');void save(String(n*100))}}>+{n}</button>)}{[1,5,10].map(n=><button type="button" key={n+'%'} disabled={blocked||!item.fields.estimated_price_cents||item.fields.estimated_price_cents==='0'} onClick={()=>{setMode('add');void save(((BigInt(item.fields.estimated_price_cents!)*BigInt(n)+50n)/100n).toString())}}>+{n}%</button>)}</div>{adding&&<><Segments label="攒钱金额方式" value={mode} options={[{value:'add',label:'本次增加'},{value:'total',label:'更正累计'}]} disabled={blocked} onChange={setMode}/><input autoFocus aria-label={mode==='add'?'本次增加金额':'累计金额'} placeholder={mode==='add'?'请输入本次金额':'请输入累计金额'} inputMode="decimal" value={amount} disabled={blocked} onChange={e=>setAmount(e.target.value)}/></>}<button type="button" className="primary save-money-button" disabled={busy||deleting||!!receipt.pending||receipt.busy} onClick={()=>{if(pending||adding)void save();else{setAdding(true);setMode('add')}}}>{pending?'重试并核对本次金额':adding?'保存金额':'存一笔'}</button></div>}{notice&&<p className="notice" role="status" ref={noticeRef}>{notice}</p>}</section>}
 <div className="inspector-metrics"><div><span>{p.mode==='savings'?'已攒':'目标日'}</span><strong>{p.mode==='savings'?money(p.saved_cents):item.fields.target_date||'待设置'}</strong></div><div><span>{p.mode==='savings'?'还差':'剩余天数'}</span><strong>{p.mode==='savings'?money(remaining):item.fields.target_date?Math.max(0,Math.ceil((Date.parse(item.fields.target_date)-Date.parse(localDay()))/86400000))+' 天':'—'}</strong></div></div>
 <section className="form-block wish-facts"><FormRow label="心愿价格">{money(item.fields.estimated_price_cents)}</FormRow><FormRow label="添加时间">{p.added_date??localDay(new Date(item.created_at))}</FormRow><FormRow label="资产分类">{taxonomy?.categories.find(c=>c.id===item.fields.category_id)?.name||'全部'}</FormRow><FormRow label="购买渠道">{taxonomy?.channels.find(c=>c.id===p.channel_id)?.name||'未选择'}</FormRow><FormRow label="心愿状态">{item.status==='achieved'?'已实现':item.status==='abandoned'?'已放弃':'进行中'}</FormRow><FormRow label="实现方式">{p.mode==='savings'?'攒钱':'倒计时'}</FormRow>{p.mode==='countdown'&&<FormRow label="目标实现时间">{item.fields.target_date||'未设置'}</FormRow>}{item.achieved_at&&<FormRow label="实现日期">{localDay(new Date(item.achieved_at))}</FormRow>}</section>
 {(item.fields.notes||item.fields.external_link||item.photos?.some(x=>x.id!==item.cover?.id))&&<section className="form-block form-notes wish-notes">{item.fields.notes&&<p className="notes">{item.fields.notes}</p>}{item.fields.external_link&&<a href={item.fields.external_link} target="_blank" rel="noreferrer">相关链接</a>}<div className="photo-strip">{item.photos?.filter(x=>x.id!==item.cover?.id).map(photo=><PhotoView key={photo.id} photo={photo} generation={generation}/>)}</div></section>}
 {item.converted_asset&&<p className="wishlist-link">关联资产：{item.converted_asset.name}{item.converted_asset.deleted?<button onClick={()=>{onClose();onOpenTrash()}}>前往最近删除</button>:<button onClick={()=>{onClose();onOpenAsset(item.converted_asset!.id)}}>查看资产</button>}</p>}</div>{p.mode!=='savings'&&notice&&<p className="notice" role="status" ref={noticeRef}>{notice}</p>}<div className="ui-foot">{item.status==='ongoing'&&!item.converted_asset&&<><button className="primary" disabled={blocked} onClick={()=>onConvert(item)}>已买到，转为物品</button><button className="ui-link" disabled={blocked} onClick={()=>onAbandon(item)}>放弃这个心愿</button></>}</div></aside>
}
