import {persistSubmission} from './editor-session';
import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {errorMessage,inputMoney,localDay,type Photo} from './asset';
import type {CloseIntent} from './AssetEditor';
import {replaceDraftCover} from './asset-media';
import {DefaultAssetIcon,IconPicker,type IconChoice} from './IconPicker';
import {PhotoView} from './Photos';
import {DateInput} from './DateInput';
import {FormRow,Switch,Segments,ChoiceField,AddImageButton,CentInput} from './FormControls';
import {allowReminders} from './NotificationNotice';
import {defaultWishPreferences} from './preferences';
import {validateWishlist,wishlistDraftKey,type WishlistDraft,type WishlistItem,type WishPlanSave} from './wishlist';
import type {TaxonomySnapshot} from './taxonomy';
export function WishlistEditor({initial,closeIntent,onKeep,onClose,onSaved}:{initial:WishlistDraft;taxonomy:TaxonomySnapshot;closeIntent:CloseIntent|null;onKeep:()=>void;onClose:(intent:CloseIntent,keep:boolean)=>void;onSaved:(i:WishlistItem)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),lock=useRef(false);
 const [draft,setDraft]=useState(initial),[busy,setBusy]=useState(false),[picker,setPicker]=useState(false),[notice,setNotice]=useState('');
 const p=draft.preferences??{...defaultWishPreferences(),added_date:localDay()},photos=draft.photos??(draft.cover?[draft.cover]:[]),pending=!!draft.planPending||!!draft.pending,disabled=busy||pending;
 useEffect(()=>{dialog.current?.showModal();return ()=>dialog.current?.close()},[]);useEffect(()=>{if(closeIntent)askClose(closeIntent)},[closeIntent]);
 function remember(next:WishlistDraft){setDraft(next);try{persistSubmission(wishlistDraftKey, next);return true}catch{setNotice('暂时无法记录保存请求，请重试。');return false}}
 function field<K extends keyof WishlistDraft['fields']>(key:K,value:WishlistDraft['fields'][K]){remember({...draft,fields:{...draft.fields,[key]:value}})}
 function prefs(part:Partial<typeof p>){remember({...draft,preferences:{...p,...part}})}
 function askClose(intent:CloseIntent){if(lock.current||pending||picker){onKeep();setNotice('请先完成当前操作或核对保存结果。');return}onClose(intent,false)}
 async function icon(choice:IconChoice){if(lock.current)return;lock.current=true;setBusy(true);try{const cover=choice.kind==='default'?null:choice.kind==='photo'?choice.photo:await invoke<Photo>('prepare_material',{input:{id:choice.entry.id,generation:draft.generation}});const next=replaceDraftCover(photos,draft.transientCover,cover,!!cover&&!photos.some(x=>x.id===cover.id));remember({...draft,cover,photos:next.photos,transientCover:next.transientCover,photoError:''})}finally{lock.current=false;setBusy(false)}}
 async function addPhoto(){if(lock.current)return;lock.current=true;setBusy(true);try{const photo=await invoke<Photo|null>('pick_photo',{generation:draft.generation,repair:null});if(photo)remember({...draft,photos:[...photos,photo],photoError:''})}catch(e){remember({...draft,photoError:errorMessage(e)})}finally{lock.current=false;setBusy(false)}}
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);try{
 if(draft.pending){const item=await invoke<WishlistItem|null>('saved_wishlist_request',{input:draft.pending});if(item){localStorage.removeItem(wishlistDraftKey);onSaved(item)}else remember({...draft,pending:null});return}
 let input=draft.planPending;
 if(!input){const errors=validateWishlist(draft.fields);if(Object.keys(errors).length){setNotice(Object.values(errors).join(' '));return}input={request_id:crypto.randomUUID(),generation:draft.generation,id:draft.item?.id??null,expected_revision:draft.item?.revision??null,fields:{...draft.fields,estimated_price_cents:inputMoney(draft.fields.estimated_price),target_date:draft.fields.target_date||null},preferences:p,photos:{ids:photos.map(x=>x.id),cover_id:draft.cover?.id??null},status_intent:draft.statusIntent??'preserve',achieved_date:draft.achievedDate??null} as WishPlanSave;delete (input.fields as unknown as Record<string,unknown>).estimated_price;if(!remember({...draft,planPending:input}))return;}
 try{const item=await invoke<WishlistItem>('save_wish_plan',{input});localStorage.removeItem(wishlistDraftKey);onSaved(item)}catch(e){try{const saved=await invoke<WishlistItem|null>('saved_wish_feature',{request:input.request_id,generation:input.generation});if(saved){localStorage.removeItem(wishlistDraftKey);onSaved(saved)}else{remember({...draft,planPending:null});setNotice(errorMessage(e))}}catch{setNotice('暂时无法核对保存结果，请重试同一请求。')}}
 }catch(e){setNotice(errorMessage(e))}finally{lock.current=false;setBusy(false)}}
 async function enableReminder(){if(lock.current)return;lock.current=true;setBusy(true);try{await allowReminders();prefs({reminder:true});setNotice('')}catch(e){setNotice(errorMessage(e))}finally{lock.current=false;setBusy(false)}}
 const achieved=draft.statusIntent==='manual'||(draft.statusIntent!=='ongoing'&&draft.item?.status==='achieved');
 return <dialog ref={dialog} className={picker?'icon-picker-host':'editor wishlist-editor'} aria-labelledby={picker?'icon-picker-title':'wishlist-editor-title'} onCancel={e=>{e.preventDefault();askClose('form')}}><form hidden={picker} onSubmit={e=>{e.preventDefault();void save()}}><header><div><p className="eyebrow">心愿清单</p><h2 id="wishlist-editor-title">{draft.item?'编辑心愿':'新增心愿'}</h2></div><button type="button" aria-label="关闭表单" onClick={()=>askClose('form')}>×</button><div className="editor-header-actions"><button type="button" disabled={disabled} onClick={()=>askClose('form')}>取消</button><button type="submit" className="primary" disabled={busy||!!draft.photoError}>{busy?'正在保存…':pending?'重试并核对保存':'保存心愿'}</button></div></header><div className="editor-body">
 <div className="asset-identity-editor"><button type="button" className="asset-avatar-button" aria-label="选择心愿图标" disabled={disabled} onClick={()=>setPicker(true)}>{draft.cover?<PhotoView photo={draft.cover} generation={draft.generation}/>:<DefaultAssetIcon/>}<span className="avatar-edit">更换图标</span></button><label className="field"><span>物品名称</span><input autoFocus placeholder="请输入物品名称" value={draft.fields.name} disabled={disabled} onChange={e=>field('name',e.target.value)}/></label></div>
 <section className="form-block"><FormRow label="心愿价格（元）"><input aria-label="心愿价格" placeholder="请输入心愿价格" inputMode="decimal" value={draft.fields.estimated_price} disabled={disabled} onChange={e=>field('estimated_price',e.target.value)}/></FormRow><FormRow label="添加时间"><DateInput label="添加时间" id="wish-added" value={p.added_date??localDay(new Date(draft.item?.created_at??Date.now()))} max={localDay()} disabled={disabled} onChange={added_date=>prefs({added_date})}/></FormRow><FormRow label="资产分类"><ChoiceField label="资产分类" kind="category" generation={draft.generation} value={draft.fields.category_id} disabled={disabled} onChange={v=>field('category_id',v)}/></FormRow><FormRow label="购买渠道"><ChoiceField label="购买渠道" kind="channel" generation={draft.generation} value={p.channel_id} disabled={disabled} onChange={channel_id=>prefs({channel_id})}/></FormRow></section>
 <section className="form-block"><FormRow label="心愿状态"><Segments label="心愿状态" value={achieved?'manual':'ongoing'} options={[{value:'ongoing',label:'未实现'},{value:'manual',label:'已实现'}]} disabled={disabled||!!draft.item?.converted_asset} onChange={statusIntent=>remember({...draft,statusIntent,achievedDate:draft.achievedDate??localDay()})}/></FormRow><FormRow label="实现方式"><Segments label="实现方式" value={p.mode} options={[{value:'countdown',label:'倒计时'},{value:'savings',label:'攒钱'}]} disabled={disabled} onChange={mode=>prefs({mode})}/></FormRow>{p.mode==='savings'?<FormRow label="已攒金额（元）" hint="达到心愿价格后自动实现"><CentInput label="累计已攒金额" placeholder="请输入累计金额" disabled={disabled} value={p.saved_cents} onChange={v=>prefs({saved_cents:v||'0'})}/></FormRow>:!achieved&&<><FormRow label="目标实现时间"><DateInput label="目标实现时间" id="wish-target" value={draft.fields.target_date} disabled={disabled} allowClear onChange={v=>field('target_date',v)}/></FormRow><FormRow label="到期通知" hint="目标日期上午 9:00 通知"><Switch label="到期通知" value={p.reminder} disabled={disabled} onChange={reminder=>{if(!reminder)prefs({reminder:false});else void enableReminder()}}/></FormRow></>}{achieved&&<FormRow label="实现时间"><DateInput label="实现时间" id="wish-achieved" value={draft.achievedDate??(draft.item?.achieved_at?localDay(new Date(draft.item.achieved_at)):localDay())} max={localDay()} disabled={disabled||!!draft.item?.converted_asset} onChange={achievedDate=>remember({...draft,statusIntent:'manual',achievedDate})}/></FormRow>}</section>
 <section className="form-block"><FormRow label="置顶心愿"><Switch label="置顶心愿" value={p.pinned} disabled={disabled} onChange={pinned=>prefs({pinned})}/></FormRow></section><section className="form-block form-notes"><textarea aria-label="心愿备注" placeholder="请输入备注信息" rows={4} value={draft.fields.notes} disabled={disabled} onChange={e=>field('notes',e.target.value)}/><div className="photo-strip">{photos.filter(x=>x.id!==draft.cover?.id).map(photo=><div className="photo-tile" key={photo.id}><PhotoView photo={photo} generation={draft.generation}/><button type="button" disabled={disabled} onClick={()=>remember({...draft,photos:photos.filter(x=>x.id!==photo.id)})}>移除</button></div>)}<AddImageButton disabled={disabled||photos.length>=20} onClick={()=>void addPhoto()}/></div></section>

 {draft.photoError&&<p role="alert">{draft.photoError}<button type="button" onClick={()=>remember({...draft,photoError:''})}>取消这次失败选图</button></p>}{notice&&<p className="notice" role="status">{notice}</p>}</div></form>{picker&&<IconPicker generation={draft.generation} photos={photos} cover={draft.cover?.id??null} onClose={()=>setPicker(false)} onUse={icon}/>}</dialog>
}
